Importing four modules (numpy, dijkstras, baseline, csv)

Numpy is used to generate the grid.

Each algorithm is it's own class and thus needs to be imported.

CSV module is used to export the results of each test to a single file.

In [1]:
#Importing algorithm classes and external modules (Numpy and CSV)
import numpy as np
from dijkstras import Dijkstras
from baseline import Baseline
import csv

full_test parameters:

runs = number of iterations to test the algorithms, for example, if runs is set to 5 it will iterate through the test 5 times per algorithm per game mode. Each iteration, ranging from sizes of 1x1 to 5x5, the grid will change and be repopulated with random numbers. Setting runs to 1000 will mean the test program will run 1000 times per game mode per algorithm totalling to 4000 runs

outText = printing test results to console, be default it is set to False to reduce time but it has been flagged as True in the main execution for demonstration purposes

outFile = prints numerical data of each test iteration to file (located at root:\\results\results.csv) at the end of the entire execution

In [2]:
#Test function
def full_test(runs, outText=False, outFile=False):
    all_results = []
    gameModes = [1, 2]
    
    #Iterating through the runs
    for i in range(1, runs + 1):
        
        #Creating the grid
        grid = np.random.randint(9, size=(i, i), dtype="uint8")
        
        #Iterating through the game modes
        for gm in gameModes:
            
            #Capturing the algorithm functions
            algorithms = [Baseline(grid), Dijkstras(grid)]
            
            #Iterating through the algorithms
            for algorithm in algorithms:
                
                #Capturing the results from each algorithm run
                time, cost, stack_size, stack = algorithm.get_results(gm)
                
                #Formatting the results
                raw_results = ("---Results---\n" +
                      "\n" +
                      "---Grid---\n" +
                      str(grid) +
                      "\n\n" +
                      "Name: " + str(algorithm.__class__.__name__) + "\n" +
                      "Game Mode: " + str(gm) + "\n" +
                      "Grid Size: " + str(i) + "\n" +
                      "Time: " + str(time) + "\n" +
                      "Cost: " + str(cost) + "\n" +
                      "Path " + str(stack) + "\n" +
                      "Stack Size: " + str(stack_size) + "\n")
   
                #Capturing results
                if time is not float("infinity"):
                    result = {"name": algorithm.__class__.__name__,
                              "size": i*i,
                              "time": time,
                              "cost": cost,
                              "stack": stack_size,
                              "mode": gm}
                    all_results.append(result)
                    
                #Printing results to console
                if outText:
                    print(raw_results)
        
        #Printing progress
        pk = float('%.10g' % (i/runs*100))
        print("Completion: " + str(pk) + "%")
        
    #Exporting results to file (excluding grid)
    if outFile:
        keys = all_results[0].keys()
        with open('results\\results.csv', 'w', newline='') as output:
            output_file = csv.DictWriter(output, keys)
            output_file.writeheader()
            output_file.writerows(all_results)
            
    print()

In [3]:
#Executing test program
if __name__ == '__main__':
    full_test(5, True)

---Results---

---Grid---
[[0]]

Name: Baseline
Game Mode: 1
Grid Size: 1
Time: 0
Cost: 0
Path [(0, 0)]
Stack Size: 1

---Results---

---Grid---
[[0]]

Name: Dijkstras
Game Mode: 1
Grid Size: 1
Time: 0
Cost: 0
Path [(0, 0)]
Stack Size: 1

---Results---

---Grid---
[[0]]

Name: Baseline
Game Mode: 2
Grid Size: 1
Time: 0
Cost: 0
Path [(0, 0)]
Stack Size: 1

---Results---

---Grid---
[[0]]

Name: Dijkstras
Game Mode: 2
Grid Size: 1
Time: 0
Cost: 0
Path [(0, 0)]
Stack Size: 1

Completion: 20.0%
---Results---

---Grid---
[[3 6]
 [7 5]]

Name: Baseline
Game Mode: 1
Grid Size: 2
Time: 0
Cost: 14
Path [(0, 0), (0, 1), (1, 1)]
Stack Size: 3

---Results---

---Grid---
[[3 6]
 [7 5]]

Name: Dijkstras
Game Mode: 1
Grid Size: 2
Time: 0
Cost: 14
Path [(0, 0), (0, 1), (1, 1)]
Stack Size: 3

---Results---

---Grid---
[[3 6]
 [7 5]]

Name: Baseline
Game Mode: 2
Grid Size: 2
Time: 0
Cost: 4
Path [(0, 0), (0, 1), (1, 1)]
Stack Size: 3

---Results---

---Grid---
[[3 6]
 [7 5]]

Name: Dijkstras
Game Mode: 